import plugin from 'tailwindcss/plugin';

import {
  borderRadius,
  borderWidths,
  boxShadow,
  colors,
  fontFamily,
  fontSize,
  fontWeight,
  lineHeight,
  opaticy,
  spacing,
} from './tokens';

export const tailwindP1mentaPlugin = plugin(
  ({ addBase, addComponents, theme }) => {
    addBase({
      html: {
        color: theme('colors.grey.800'),
        backgroundColor: theme('colors.white'),
      },
      '*': {
        borderColor: theme('colors.grey.300'),
      },
    });
    addComponents({
      '.label-sm': {
        fontSize: theme('fontSize.xxs'),
        fontWeight: theme('fontWeight.bold'),
        lineHeight: theme('lineHeight.far'),
      },
      '.label-md': {
        fontSize: theme('fontSize.xs'),
        fontWeight: theme('fontWeight.bold'),
        lineHeight: theme('lineHeight.far'),
      },
      '.caption-sm-heavy': {
        fontSize: theme('fontSize.xxxs'),
        fontWeight: theme('fontWeight.bold'),
        lineHeight: theme('lineHeight.far'),
      },
      '.paragraph-sm': {
        fontSize: theme('fontSize.xxs'),
        fontWeight: theme('fontWeight.relular'),
        lineHeight: theme('lineHeight.far'),
      },
      '.paragraph-md': {
        fontSize: theme('fontSize.xs'),
        fontWeight: theme('fontWeight.relular'),
        lineHeight: theme('lineHeight.far'),
      },
      '.display-sm-heavy': {
        fontSize: theme('fontSize.xl'),
        fontWeight: theme('fontWeight.demibold'),
        lineHeight: theme('lineHeight.far'),
      },
      '.heading-xs-heavy': {
        fontSize: theme('fontSize.sm'),
        fontWeight: theme('fontWeight.bold'),
        lineHeight: theme('lineHeight.far'),
      },
      '.heading-sm': {
        fontSize: theme('fontSize.md'),
        fontWeight: theme('fontWeight.demibold'),
        lineHeight: theme('lineHeight.compact'),
      },
    });
  },
  {
    theme: {
      screens: {
        xs: '360px',
        sm: '576px',
        md: '768px',
        lg: '992px',
        xl: '1200px',
      },
      extend: {
        colors: {
          brand: {
            950: colors['--color-brand-950'],
            900: colors['--color-brand-900'],
            800: colors['--color-brand-800'],
            700: colors['--color-brand-700'],
            600: colors['--color-brand-600'],
            500: colors['--color-brand-500'],
            400: colors['--color-brand-400'],
            300: colors['--color-brand-300'],
            200: colors['--color-brand-200'],
            100: colors['--color-brand-100'],
            50: colors['--color-brand-50'],
          },
          neutral: {
            1000: colors['--color-neutral-1000'],
            950: colors['--color-neutral-950'],
            900: colors['--color-neutral-900'],
            800: colors['--color-neutral-800'],
            700: colors['--color-neutral-700'],
            600: colors['--color-neutral-600'],
            500: colors['--color-neutral-500'],
            400: colors['--color-neutral-400'],
            300: colors['--color-neutral-300'],
            200: colors['--color-neutral-200'],
            100: colors['--color-neutral-100'],
            50: colors['--color-neutral-50'],
            0: colors['--color-neutral-0'],
          },
          red: {
            950: colors['--color-red-950'],
            900: colors['--color-red-900'],
            800: colors['--color-red-800'],
            700: colors['--color-red-700'],
            600: colors['--color-red-600'],
            500: colors['--color-red-500'],
            400: colors['--color-red-400'],
            300: colors['--color-red-300'],
            200: colors['--color-red-200'],
            100: colors['--color-red-100'],
            50: colors['--color-red-50'],
          },
          yellow: {
            950: colors['--color-yellow-950'],
            900: colors['--color-yellow-900'],
            800: colors['--color-yellow-800'],
            700: colors['--color-yellow-700'],
            600: colors['--color-yellow-600'],
            500: colors['--color-yellow-500'],
            400: colors['--color-yellow-400'],
            300: colors['--color-yellow-300'],
            200: colors['--color-yellow-200'],
            100: colors['--color-yellow-100'],
            50: colors['--color-yellow-50'],
          },
          emerald: {
            950: colors['--color-emerald-950'],
            900: colors['--color-emerald-900'],
            800: colors['--color-emerald-800'],
            700: colors['--color-emerald-700'],
            600: colors['--color-emerald-600'],
            500: colors['--color-emerald-500'],
            400: colors['--color-emerald-400'],
            300: colors['--color-emerald-300'],
            200: colors['--color-emerald-200'],
            100: colors['--color-emerald-100'],
            50: colors['--color-emerald-50'],
          },
          cyan: {
            950: colors['--color-cyan-950'],
            900: colors['--color-cyan-900'],
            800: colors['--color-cyan-800'],
            700: colors['--color-cyan-700'],
            600: colors['--color-cyan-600'],
            500: colors['--color-cyan-500'],
            400: colors['--color-cyan-400'],
            300: colors['--color-cyan-300'],
            200: colors['--color-cyan-200'],
            100: colors['--color-cyan-100'],
            50: colors['--color-cyan-50'],
          },
          purple: {
            950: colors['--color-purple-950'],
            900: colors['--color-purple-900'],
            800: colors['--color-purple-800'],
            700: colors['--color-purple-700'],
            600: colors['--color-purple-600'],
            500: colors['--color-purple-500'],
            400: colors['--color-purple-400'],
            300: colors['--color-purple-300'],
            200: colors['--color-purple-200'],
            100: colors['--color-purple-100'],
            50: colors['--color-purple-50'],
          },
          pink: {
            950: colors['--color-pink-950'],
            900: colors['--color-pink-900'],
            800: colors['--color-pink-800'],
            700: colors['--color-pink-700'],
            600: colors['--color-pink-600'],
            500: colors['--color-pink-500'],
            400: colors['--color-pink-400'],
            300: colors['--color-pink-300'],
            200: colors['--color-pink-200'],
            100: colors['--color-pink-100'],
            50: colors['--color-pink-50'],
          },
        },
        borderRadius: {
          none: borderRadius['--border-radius-none'],
          sm: borderRadius['--border-radius-sm'],
          default: borderRadius['--border-radius-default'],
          lg: borderRadius['--border-radius-lg'],
          full: borderRadius['--border-radius-full'],
        },
        fontSize: {
          xxxs: fontSize['--font-size-xxxs'],
          xxs: fontSize['--font-size-xxs'],
          xs: fontSize['--font-size-xs'],
          sm: fontSize['--font-size-sm'],
          md: fontSize['--font-size-md'],
          lg: fontSize['--font-size-lg'],
          xl: fontSize['--font-size-xl'],
          xxl: fontSize['--font-size-xxl'],
          xxxl: fontSize['--font-size-xxxl'],
          giant: fontSize['--font-size-giant'],
          huge: fontSize['--font-size-huge'],
        },
        lineHeight: {
          near: lineHeight['--line-height-near'],
          compact: lineHeight['--line-height-compact'],
          far: lineHeight['--line-height-far'],
        },
        fontWeight: {
          regular: fontWeight['--font-weight-regular'],
          medium: fontWeight['--font-weight-medium'],
          semibold: fontWeight['--font-weight-semibold'],
        },
        fontFamily: {
          mono: fontFamily['--font-mono'],
          sans: fontFamily['--font-sans'],
        },
        boxShadow: {
          level1: boxShadow['--shadow-level-1'],
          level2: boxShadow['--shadow-level-2'],
          level3: boxShadow['--shadow-level-3'],
          level4: boxShadow['--shadow-level-4'],
        },
        borderWidth: {
          0: borderWidths['--border-width-0'],
          1: borderWidths['--border-width-1'],
          2: borderWidths['--border-width-2'],
        },
        opacity: {
          visible: opaticy['--opacity-visible'],
          hover: opaticy['--opacity-hover'],
          disabled: opaticy['--opacity-disabled'],
          loading: opaticy['--opacity-loading'],
          invisible: opaticy['--opacity-invisible'],
        },
        spacing: {
          0: spacing['--spacing-0'],
          1: spacing['--spacing-1'],
          2: spacing['--spacing-2'],
          3: spacing['--spacing-3'],
          4: spacing['--spacing-4'],
          5: spacing['--spacing-5'],
          6: spacing['--spacing-6'],
          7: spacing['--spacing-7'],
          8: spacing['--spacing-8'],
          9: spacing['--spacing-9'],
          10: spacing['--spacing-10'],
          11: spacing['--spacing-11'],
          12: spacing['--spacing-12'],
          14: spacing['--spacing-14'],
          16: spacing['--spacing-16'],
          20: spacing['--spacing-20'],
          24: spacing['--spacing-24'],
          28: spacing['--spacing-28'],
          32: spacing['--spacing-32'],
          36: spacing['--spacing-36'],
          40: spacing['--spacing-40'],
          44: spacing['--spacing-44'],
          48: spacing['--spacing-48'],
          52: spacing['--spacing-52'],
          56: spacing['--spacing-56'],
          60: spacing['--spacing-60'],
          64: spacing['--spacing-64'],
          72: spacing['--spacing-72'],
          80: spacing['--spacing-80'],
          96: spacing['--spacing-96'],
        },
      },
    },
  },
);
